baseURL = 'https://langroid.github.io/blog'
languageCode = 'en-us'
title = 'Langroid Blog'
theme = 'PaperMod'


[params]
author = "Prasad Chalasani"
description = "Langroid news and musings"
math = "mathjax"

[[params.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/langroid/langroid"

[[params.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/pchalasani"
